---
ID: "9a40b487-aa50-4d17-9313-1d61ab86d622"
Parent: "0a873bab-31d1-445a-ac16-14d62ab62c98"
Template: "0a873bab-31d1-445a-ac16-14d62ab62c98"
Path: /sitecore/templates/Project/BrooksRunning/Product Grid Product/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20261007T230000Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\uOsH5C0aan6uFWJMjpdHZ7IMjCUqv6Ur
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\uOsH5C0aan6uFWJMjpdHZ7IMjCUqv6Ur
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "336bdfbb-f026-4dd5-aee3-dfa0c4970b6e"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\uOsH5C0aan6uFWJMjpdHZ7IMjCUqv6Ur
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20261007T230906Z
